apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: category-service
  name: category-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-service
  strategy: {}
  template:
    metadata:

      labels:
        app: category-service
    spec:
      containers:
        - env:
            - name: profile
              value: "default"
            - name: eureka.client.serviceUrl.defaultZone
              value: "http://discovery-server:8888/eureka"
            - name: eureka.instance.hostname
              value: "category-service"
            - name: eureka.instance.preferIpAddress
              value: "true"
          image: iliassoltani/category-image:latest
          name: category-service
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: category-service
  name: category-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: category-service

