apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-formation
  name: ms-formation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-formation
  strategy: {}
  template:
    metadata:

      labels:
        app: ms-formation
    spec:
      containers:
        - env:
            - name: profile
              value: "default"
            - name: eureka.client.serviceUrl.defaultZone
              value: "http://discovery-server:8888/eureka"
            - name: eureka.instance.hostname
              value: "ms-formation"
            - name: eureka.instance.preferIpAddress
              value: "true"
          image: iliassoltani/msformation-image:latest
          name: ms-formation
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-formation
  name: ms-formation
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: ms-formation

