apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy: {}
  template:
    metadata:

      labels:
        app: order-service
    spec:
      containers:
        - env:
            - name: profile
              value: "default"
            - name: eureka.client.serviceUrl.defaultZone
              value: "http://discovery-server:8888/eureka"
            - name: eureka.instance.hostname
              value: "order-service"
            - name: eureka.instance.preferIpAddress
              value: "true"
          image: iliassoltani/order-image:latest
          name: order-service
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: order-service

