apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-service
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  strategy: {}
  template:
    metadata:

      labels:
        app: payment-service
    spec:
      containers:
        - env:
            - name: profile
              value: "default"
            - name: eureka.client.serviceUrl.defaultZone
              value: "http://discovery-server:8888/eureka"
            - name: eureka.instance.hostname
              value: "payment-service"
            - name: eureka.instance.preferIpAddress
              value: "true"
          image: iliassoltani/payment-image:latest
          name: payment-service
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment-service
  name: payment-service
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: payment-service

