apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy: {}
  template:
    metadata:

      labels:
        app: product-service
    spec:
      containers:
        - env:
            - name: profile
              value: "default"
            - name: eureka.client.serviceUrl.defaultZone
              value: "http://discovery-server:8888/eureka"
            - name: eureka.instance.hostname
              value: "product-service"
            - name: eureka.instance.preferIpAddress
              value: "true"
          image: iliassoltani/product-image:latest
          name: product-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: product-service

