apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  PORT: "8000"
  NODE_ENV: "development"
  DB_URL: "mongodb+srv://admin:RTHXlx5S0v43IfJb@ms-authentication.sr60fcd.mongodb.net/ms-authentication?retryWrites=true&w=majority&appName=ms-authentication"
  JWT_SECRET_KEY: "jwt-secret-key-in-website-is-west-hello-wolrd"
  TOKEN_EXPIRES_IN: "90d"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8888/eureka"
  HOSTNAME: "user-service"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "465"
  EMAIL_USER: "buy.it.production@gmail.com"
  EUREKA_HOST: "discovery-server"
  API_KEY: "AIzaSyDkpxh-5_H9hKNcbSWytyhw5jVMISYPerc"
  AUTH_DOMAIN: "projet-4eme.firebaseapp.com"
  PROJECT_ID: "projet-4eme"
  STORAGE_BUCKET: "projet-4eme.appspot.com"
  MESSAGING_SENDER_ID: "1087934820851"
  APP_ID: "1:1087934820851:web:a01e527b4dae8e17736286"
  MEASUREMENT_ID: "G-TBEKK6931N"
  EMAIL_PASSWORD: "aikamomzcdjmwztc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy: {}
  template:
    metadata:

      labels:
        app: user-service
    spec:
      containers:
        - image: iliassoltani/user-image:latest
          name: user-service
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: user-service-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: user-service

